name: Build documentation

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cmake pybind11 numpy tox assorthead mattress>=0.1.4

      - name: Build docs
        run: |
          python setup.py build_ext --inplace
          cp build/lib*/scranpy/lib_scranpy* src/scranpy/
          tox -e docs
          touch ./docs/_build/html/.nojekyll

      - name: GH Pages Deployment
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/_build/html
          clean: true # Automatically remove deleted files from the deploy branch
